/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as AddIndexRouteImport } from './routes/add.index'
import { Route as AddManualRouteImport } from './routes/add.manual'
import { Route as AddPhotoRouteImport } from './routes/add.photo'
import { Route as AddVoiceRouteImport } from './routes/add.voice'
import { Route as BuyersIndexRouteImport } from './routes/buyers.index'
import { Route as BuyersIdRouteImport } from './routes/buyers.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIndexRoute = AddIndexRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddManualRoute = AddManualRouteImport.update({
  id: '/add/manual',
  path: '/add/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPhotoRoute = AddPhotoRouteImport.update({
  id: '/add/photo',
  path: '/add/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const AddVoiceRoute = AddVoiceRouteImport.update({
  id: '/add/voice',
  path: '/add/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersIndexRoute = BuyersIndexRouteImport.update({
  id: '/buyers/',
  path: '/buyers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersIdRoute = BuyersIdRouteImport.update({
  id: '/buyers/$id',
  path: '/buyers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/add/manual': typeof AddManualRoute
  '/add/photo': typeof AddPhotoRoute
  '/add/voice': typeof AddVoiceRoute
  '/buyers/$id': typeof BuyersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/add/': typeof AddIndexRoute
  '/buyers/': typeof BuyersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/add/manual': typeof AddManualRoute
  '/add/photo': typeof AddPhotoRoute
  '/add/voice': typeof AddVoiceRoute
  '/buyers/$id': typeof BuyersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/add': typeof AddIndexRoute
  '/buyers': typeof BuyersIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/add/manual': typeof AddManualRoute
  '/add/photo': typeof AddPhotoRoute
  '/add/voice': typeof AddVoiceRoute
  '/buyers/$id': typeof BuyersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/add/': typeof AddIndexRoute
  '/buyers/': typeof BuyersIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/publish'
    | '/add/manual'
    | '/add/photo'
    | '/add/voice'
    | '/buyers/$id'
    | '/products/$id'
    | '/add/'
    | '/buyers/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/publish'
    | '/add/manual'
    | '/add/photo'
    | '/add/voice'
    | '/buyers/$id'
    | '/products/$id'
    | '/add'
    | '/buyers'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/publish'
    | '/add/manual'
    | '/add/photo'
    | '/add/voice'
    | '/buyers/$id'
    | '/products/$id'
    | '/add/'
    | '/buyers/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  PublishRoute: typeof PublishRoute
  AddManualRoute: typeof AddManualRoute
  AddPhotoRoute: typeof AddPhotoRoute
  AddVoiceRoute: typeof AddVoiceRoute
  BuyersIdRoute: typeof BuyersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  AddIndexRoute: typeof AddIndexRoute
  BuyersIndexRoute: typeof BuyersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/': {
      id: '/add/'
      path: '/add'
      fullPath: '/add/'
      preLoaderRoute: typeof AddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/manual': {
      id: '/add/manual'
      path: '/add/manual'
      fullPath: '/add/manual'
      preLoaderRoute: typeof AddManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/photo': {
      id: '/add/photo'
      path: '/add/photo'
      fullPath: '/add/photo'
      preLoaderRoute: typeof AddPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/voice': {
      id: '/add/voice'
      path: '/add/voice'
      fullPath: '/add/voice'
      preLoaderRoute: typeof AddVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers/': {
      id: '/buyers/'
      path: '/buyers'
      fullPath: '/buyers/'
      preLoaderRoute: typeof BuyersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers/$id': {
      id: '/buyers/$id'
      path: '/buyers/$id'
      fullPath: '/buyers/$id'
      preLoaderRoute: typeof BuyersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  PublishRoute: PublishRoute,
  AddManualRoute: AddManualRoute,
  AddPhotoRoute: AddPhotoRoute,
  AddVoiceRoute: AddVoiceRoute,
  BuyersIdRoute: BuyersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  AddIndexRoute: AddIndexRoute,
  BuyersIndexRoute: BuyersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
